CREATE EXTENSION IF NOT EXISTS postgis;
select * from public.app_user;
create table public.app_user
(
    id       uuid default gen_random_uuid() not null
        constraint app_user_pk
            primary key,
    name     varchar(30)                    not null,
    email    varchar(30)                    not null
        constraint check_mail
            check ((email)::text ~~ '%@%'::text),
    position geometry
        constraint check_geometry
            check (st_geometrytype("position") = 'ST_Point'::text)
);

comment on table public.app_user is 'All the registered users on the map app';

comment on column public.app_user.id is 'This field might be autogenerated ';

comment on constraint app_user_pk on public.app_user is 'This field is the primary key ';

comment on column public.app_user.name is 'This might be the real name of the user';

comment on constraint check_mail on public.app_user is 'The email must have : @';

comment on column public.app_user.position is 'his';

comment on constraint check_geometry on public.app_user is 'The geometry of the field must be punctual ';

alter table public.app_user
    owner to postgres;

