name = "map-project-backend"
main = "src/index.ts"
compatibility_date = "2026-06-05"

[[d1_databases]]
binding = "DB"
database_name = "map-project-db"
database_id = "map-project-db-local"

[[r2_buckets]]
binding = "R2"
bucket_name = "map-project-images"

[env.production.vars]
NODE_ENV = "production"

[env.development.vars]
NODE_ENV = "development"
TRUSTED_ORIGINS = "http://localhost:5173"
